[2023-07-02T12:17:13.601+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_db.extract_data_id manual__2023-07-02T11:17:03.959768+00:00 [queued]>
[2023-07-02T12:17:13.609+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_db.extract_data_id manual__2023-07-02T11:17:03.959768+00:00 [queued]>
[2023-07-02T12:17:13.609+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-02T12:17:13.619+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_id> on 2023-07-02 11:17:03.959768+00:00
[2023-07-02T12:17:13.622+0100] {standard_task_runner.py:57} INFO - Started process 8610 to run task
[2023-07-02T12:17:13.625+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'init_db', 'extract_data_id', 'manual__2023-07-02T11:17:03.959768+00:00', '--job-id', '31', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/init_db.py', '--cfg-path', '/tmp/tmp__9u1d7f']
[2023-07-02T12:17:13.627+0100] {standard_task_runner.py:85} INFO - Job 31: Subtask extract_data_id
[2023-07-02T12:17:13.688+0100] {task_command.py:410} INFO - Running <TaskInstance: init_db.extract_data_id manual__2023-07-02T11:17:03.959768+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-02T12:17:13.779+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_db' AIRFLOW_CTX_TASK_ID='extract_data_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T11:17:03.959768+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T11:17:03.959768+00:00'
[2023-07-02T12:17:16.890+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/haboubi/Desktop/api/API_weather/./dags/hist_day_data_fetch.py", line 123, in save_pd_csv
    df,location_df=create_hist_day_data_pd_total(location_df,city=c)
  File "/home/haboubi/Desktop/api/API_weather/./dags/hist_day_data_fetch.py", line 75, in create_hist_day_data_pd_total
    location_df.loc[len(location_df)]=list(location.values)+[df.loc[df.index[-1]]]
TypeError: 'builtin_function_or_method' object is not iterable
[2023-07-02T12:17:16.928+0100] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=init_db, task_id=extract_data_id, execution_date=20230702T111703, start_date=20230702T111713, end_date=20230702T111716
[2023-07-02T12:17:16.946+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task extract_data_id ('builtin_function_or_method' object is not iterable; 8610)
[2023-07-02T12:17:16.971+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T12:17:17.002+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
