[2023-07-02T12:16:32.793+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_db.extract_data_id manual__2023-07-02T11:16:29.359564+00:00 [queued]>
[2023-07-02T12:16:32.803+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_db.extract_data_id manual__2023-07-02T11:16:29.359564+00:00 [queued]>
[2023-07-02T12:16:32.803+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-02T12:16:32.817+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): extract_data_id> on 2023-07-02 11:16:29.359564+00:00
[2023-07-02T12:16:32.821+0100] {standard_task_runner.py:57} INFO - Started process 8165 to run task
[2023-07-02T12:16:32.824+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'init_db', 'extract_data_id', 'manual__2023-07-02T11:16:29.359564+00:00', '--job-id', '29', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/init_db.py', '--cfg-path', '/tmp/tmpw0z6ffds']
[2023-07-02T12:16:32.826+0100] {standard_task_runner.py:85} INFO - Job 29: Subtask extract_data_id
[2023-07-02T12:16:32.896+0100] {task_command.py:410} INFO - Running <TaskInstance: init_db.extract_data_id manual__2023-07-02T11:16:29.359564+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-02T12:16:33.012+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_db' AIRFLOW_CTX_TASK_ID='extract_data_id' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T11:16:29.359564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-02T11:16:29.359564+00:00'
[2023-07-02T12:16:36.203+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/haboubi/Desktop/api/API_weather/./dags/hist_day_data_fetch.py", line 123, in save_pd_csv
    df,location_df=create_hist_day_data_pd_total(location_df,city=c)
  File "/home/haboubi/Desktop/api/API_weather/./dags/hist_day_data_fetch.py", line 75, in create_hist_day_data_pd_total
    location_df.loc[len(location_df)]=list(location.values)+[df.loc[df.index[-1]]]
TypeError: 'builtin_function_or_method' object is not iterable
[2023-07-02T12:16:36.254+0100] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=init_db, task_id=extract_data_id, execution_date=20230702T111629, start_date=20230702T111632, end_date=20230702T111636
[2023-07-02T12:16:36.286+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task extract_data_id ('builtin_function_or_method' object is not iterable; 8165)
[2023-07-02T12:16:36.328+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-02T12:16:36.369+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
