[2023-07-03T16:23:33.743+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:23:33.752+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:23:33.753+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-07-03T16:23:33.764+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): trigger_db> on 2023-07-01 00:00:00+00:00
[2023-07-03T16:23:33.768+0100] {standard_task_runner.py:57} INFO - Started process 14026 to run task
[2023-07-03T16:23:33.772+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'updated_day_hist', 'trigger_db', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py', '--cfg-path', '/tmp/tmp4q9_2kdv']
[2023-07-03T16:23:33.773+0100] {standard_task_runner.py:85} INFO - Job 45: Subtask trigger_db
[2023-07-03T16:23:33.838+0100] {task_command.py:410} INFO - Running <TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-03T16:23:33.939+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='updated_day_hist' AIRFLOW_CTX_TASK_ID='trigger_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-07-03T16:23:33.941+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py", line 19, in trigger_database_dag
    info=trigger_database()
TypeError: trigger_database() missing 1 required positional argument: 'locations'
[2023-07-03T16:23:33.955+0100] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=updated_day_hist, task_id=trigger_db, execution_date=20230701T000000, start_date=20230703T152333, end_date=20230703T152333
[2023-07-03T16:23:33.969+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 45 for task trigger_db (trigger_database() missing 1 required positional argument: 'locations'; 14026)
[2023-07-03T16:23:33.984+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-03T16:23:34.053+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-03T16:48:32.053+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:48:32.064+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:48:32.064+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-07-03T16:48:32.077+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): trigger_db> on 2023-07-01 00:00:00+00:00
[2023-07-03T16:48:32.082+0100] {standard_task_runner.py:57} INFO - Started process 22787 to run task
[2023-07-03T16:48:32.085+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'updated_day_hist', 'trigger_db', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py', '--cfg-path', '/tmp/tmpevm3mq_2']
[2023-07-03T16:48:32.086+0100] {standard_task_runner.py:85} INFO - Job 87: Subtask trigger_db
[2023-07-03T16:48:32.157+0100] {task_command.py:410} INFO - Running <TaskInstance: updated_day_hist.trigger_db scheduled__2023-07-01T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-03T16:48:32.278+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='updated_day_hist' AIRFLOW_CTX_TASK_ID='trigger_db' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-07-03T16:48:32.320+0100] {python.py:183} INFO - Done. Returned value was: None
[2023-07-03T16:48:32.337+0100] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=updated_day_hist, task_id=trigger_db, execution_date=20230701T000000, start_date=20230703T154832, end_date=20230703T154832
[2023-07-03T16:48:32.377+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-03T16:48:32.417+0100] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
